#!/usr/bin/env python3
import argparse
from pathlib import Path


def raw_literal(name, text):
    base = f"SHELF_{name}"
    delim = base
    suffix = f"){delim}\""
    i = 0
    while suffix in text:
        i += 1
        delim = f"{base}_{i}"
        suffix = f"){delim}\""
    return f'R"{delim}({text}){delim}"'


def main():
    parser = argparse.ArgumentParser(description="Generate C++ sources with embedded scene maps.")
    parser.add_argument("--scene-dir", required=True, type=Path)
    parser.add_argument("--out-cpp", required=True, type=Path)
    parser.add_argument("--out-hpp", required=True, type=Path)
    args = parser.parse_args()

    maps = []
    for map_dir in sorted(args.scene_dir.iterdir(), key=lambda p: int(p.name) if p.name.isdigit() else p.name):
        if not map_dir.is_dir() or not map_dir.name.isdigit():
            continue
        json_path = map_dir / "buildConstData.json"
        if json_path.is_file():
            maps.append((int(map_dir.name), json_path.read_text(encoding="utf-8")))

    args.out_hpp.parent.mkdir(parents=True, exist_ok=True)
    args.out_cpp.parent.mkdir(parents=True, exist_ok=True)

    args.out_hpp.write_text(
        """#pragma once

#include <string_view>
#include <vector>

namespace shelf {
    std::string_view embeddedMapJson(int map_index);
    bool hasEmbeddedMap(int map_index);
    std::vector<int> embeddedMapIndexes();
}
""",
        encoding="utf-8",
    )

    lines = [
        "// Generated by scripts/embed_maps.py. Do not edit.",
        "",
        '#include "embedded_maps.hpp"',
        "",
        "#include <array>",
        "",
        "namespace shelf {",
        "    namespace {",
        "        struct EmbeddedMapEntry {",
        "            int index;",
        "            std::string_view json;",
        "        };",
        "",
    ]

    for index, text in maps:
        lines.append(f"        constexpr std::string_view kMap{index} = {raw_literal(f'MAP_{index}', text)};")
        lines.append("")

    lines.append("        constexpr std::array<EmbeddedMapEntry, %d> kEmbeddedMaps{{" % len(maps))
    for index, _ in maps:
        lines.append(f"            {{{index}, kMap{index}}},")
    lines.extend(
        [
            "        }};",
            "    }",
            "",
            "    std::string_view embeddedMapJson(int map_index) {",
            "        for (const auto &entry: kEmbeddedMaps) {",
            "            if (entry.index == map_index) return entry.json;",
            "        }",
            "        return {};",
            "    }",
            "",
            "    bool hasEmbeddedMap(int map_index) {",
            "        return !embeddedMapJson(map_index).empty();",
            "    }",
            "",
            "    std::vector<int> embeddedMapIndexes() {",
            "        std::vector<int> indexes;",
            "        indexes.reserve(kEmbeddedMaps.size());",
            "        for (const auto &entry: kEmbeddedMaps) indexes.push_back(entry.index);",
            "        return indexes;",
            "    }",
            "}",
            "",
        ]
    )
    args.out_cpp.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
